# Generated by Django 2.2.10 on 2021-01-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210124_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('TEXT', 'Free Text'), ('ONE', 'One from list'), ('MANY', 'Many from list')], default=('TEXT', 'Free Text'), max_length=128),
        ),
    ]
