# Generated by Django 2.2.10 on 2021-01-25 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210124_1944'),
    ]

    operations = [

        migrations.AlterField(
            model_name='answer',
            name='many',
            field=models.ManyToManyField(blank=True, related_name='answers', to='core.Choice'),
        ),
        migrations.AlterField(
            model_name='question',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.Poll'),
        ),
    ]
