# Generated by Django 2.2.10 on 2021-01-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_answer_poll'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
