# Generated by Django 2.2.10 on 2021-01-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_answer_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('user', 'poll', 'question'), name='unique answer'),
        ),
    ]
